### PR TITLE
Move to avoid conflict.

### PR DESCRIPTION
**Pull request by samth**

### CODE REVIEW

**Comment by samth** [comment]
Ping.

**Comment by bb010g** [comment]
LGTM.

**Comment by stephanh42** [comment]
?
Op 18 mei 2015 22:13 schreef "Sam Tobin-Hochstadt" <notifications@github.com

**Comment by stephanh42** [comment]
LGTM?
Op 18 mei 2015 22:47 schreef "Brayden" <notifications@github.com>:

**Comment by bb010g** [comment]
Looks Good To Me

**Comment by samth** [comment]
@stephanh42 Can you merge this?

**Pull request merged**
